name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: never

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      COMPOSE_BAKE: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build and test script
      run: ./scripts/build.sh
